name: real_state
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  cached_network_image: ^3.3.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  easy_localization: ^3.0.7
  http: ^1.1.2
  dartz: ^0.10.1
  go_router: ^14.1.4
  get_it: ^7.6.7
  logger: ^2.0.2+1

  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5
  loading_animation_widget: ^1.2.0+4
  flutter_inset_box_shadow: ^1.0.8
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  bottom_navy_bar: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  multi_select_flutter: ^4.1.3
  country_picker: ^2.0.26
  font_awesome_flutter: ^10.7.0
  dotted_line: ^3.2.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  webview_flutter_wkwebview: ^3.10.0
  webview_flutter_android: ^3.16.0
  otpless_flutter: 2.1.2
  device_preview: ^1.2.0
  country_state_city: ^0.1.6
  file_picker: ^8.0.6
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+1
  carousel_slider: ^4.2.1
  gallery_image_viewer: ^1.2.0
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/icons/
    - assets/svgs/images/
    - assets/translations/


  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Black.otf
        - asset: assets/fonts/Switzer-Extrabold.otf
        - asset: assets/fonts/Switzer-Bold.otf
        - asset: assets/fonts/Switzer-Semibold.otf
        - asset: assets/fonts/Switzer-Medium.otf
        - asset: assets/fonts/Switzer-Regular.otf
        - asset: assets/fonts/Switzer-Light.otf
        - asset: assets/fonts/Switzer-Extralight.otf
        - asset: assets/fonts/Switzer-Thin.otf